### ISSUE TITLE
Some suggestions for CSS code formatting. 

### ISSUE THREAD

**Issue by josephtkim** [Ryoiwa/f1-3-c2p1-colmar-academy#5]
There are some suggestions to improve the formatting of your CSS code. 

First is to always try to stay consistent with how you format everything, which includes how much you indent each line, and how much empty space is between each selector. For the first several lines of the code, there are some inconsistencies with the formatting. 

https://github.com/Ryoiwa/f1-3-c2p1-colmar-academy/blob/master/capstone/resources/css/style.css#L1-L21

Another suggestion for the code is to use less space per indentation, to reduce white space and make the code easier to read. 

Here is how you might apply these to the code

```css
html {
  font-family: "Helvetica", sans-serif;
  font-size: 16px;
}

body {
  margin: 0;
  color: #5f5f5f;
}

.mobile {
  display: none;
}

.main-content {
  display: block;
  width: 100%;
  top: 64px;
}
```
